### ISSUE TITLE
docker-compose exits instantly

### ISSUE THREAD

**Issue by derbernhard** [t3r/vzlogger-docker#1]
hi, found your docker image on docker hub and have little problems with it..
here is my docker-compose log:
[Apr 16 05:38:11][main] vzlogger v0.8.0 based on heads/master-0-g8d06176360 from Sat, 18 Jan 2020 09:23:08 +0100 started.
[Apr 16 05:38:11][push] Ignoring push entry due to empty array or duplicate section
[Apr 16 05:38:11][mtr0] Creating new meter with protocol d0.
[Apr 16 05:38:11][d0]   pullseq len:5 found
[Apr 16 05:38:11][d0]   ackseq len:6 found 050
, 6
[Apr 16 05:38:11][mtr0] Meter configured, enabled.
[Apr 16 05:38:11]       New meter initialized (protocol=d0)
[Apr 16 05:38:11]       Configure channel.
[Apr 16 05:38:11][chn0] New channel initialized (uuid=... api=volkszaehler id=1-0:1.8.1)
[Apr 16 05:38:11]       Have 1 meters.
[Apr 16 05:38:11][main] log level is 15
[Apr 16 05:38:11][main] daemon=1, local=1
[Apr 16 05:38:11]       Daemonize process...

After that, container exits instantly. So container is up for 1s and stops.
Do you have any clue whats wrong?

**Comment by t3r** [comment]
Don't let it daemonize. This will let the main process exit which stops the container.

Add

`"daemon": false`

to your vzlogger.conf. This should keep the container running.

**Comment by derbernhard** [comment]
wow. thank you for the very quick response. That did the trick.

**Comment by t3r** [comment]
Thanks for reporting. I shall add it to the readme.
