### ISSUE TITLE
Can't open device /dev/ttyUSB0

### ISSUE THREAD

**Issue by Benny-Git** [t3r/vzlogger-docker#2]
I tried getting my USB IR head to work with this container, but ran into issues where it could not open the meter:

```
[Oct 07 20:59:39][]     ===> Start meters
[Oct 07 20:59:39][sml]  open(/dev/ttyUSB0): Permission denied
[Oct 07 20:59:39][mtr0] Cannot open meter
[Oct 07 20:59:39][]     Startup failed: Meter open failed.
```

I finally figured out that the user doesn't have the right permissions, as `USER nobody` is set in the Dockerfile. Is there a specific reason for this? Otherwise please accept my pull request to change this.

**Comment by t3r** [comment]
Running as root is dangerous and should not be the default setting. You can run your docker image as root with
"docker run [...] --user root [..]"
and override the USER setting in the Dockerfile
